# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Readerinfo_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 252)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 121, 251))
        self.widget_2.setObjectName("widget_2")
        self.min_bt = QtWidgets.QPushButton(self.widget_2)
        self.min_bt.setGeometry(QtCore.QRect(20, 10, 15, 15))
        self.min_bt.setMaximumSize(QtCore.QSize(15, 15))
        self.min_bt.setText("")
        self.min_bt.setObjectName("min_bt")
        self.none_bt = QtWidgets.QPushButton(self.widget_2)
        self.none_bt.setGeometry(QtCore.QRect(50, 10, 15, 15))
        self.none_bt.setMaximumSize(QtCore.QSize(15, 15))
        self.none_bt.setText("")
        self.none_bt.setObjectName("none_bt")
        self.close_bt = QtWidgets.QPushButton(self.widget_2)
        self.close_bt.setGeometry(QtCore.QRect(80, 10, 15, 15))
        self.close_bt.setMaximumSize(QtCore.QSize(15, 15))
        self.close_bt.setText("")
        self.close_bt.setObjectName("close_bt")
        self.pic_label = QtWidgets.QLabel(self.widget_2)
        self.pic_label.setGeometry(QtCore.QRect(20, 50, 91, 141))
        self.pic_label.setText("")
        self.pic_label.setObjectName("pic_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 130, 160, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.dept_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.dept_label.setText("")
        self.dept_label.setObjectName("dept_label")
        self.horizontalLayout.addWidget(self.dept_label)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 90, 160, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.sex_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.sex_label.setText("")
        self.sex_label.setObjectName("sex_label")
        self.horizontalLayout_2.addWidget(self.sex_label)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 10, 160, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_3.addWidget(self.label_1)
        self.name_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_3.addWidget(self.name_label)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(140, 50, 160, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.id_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.id_label.setText("")
        self.id_label.setObjectName("id_label")
        self.horizontalLayout_4.addWidget(self.id_label)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(120, 0, 211, 251))
        self.widget_3.setObjectName("widget_3")
        self.delete_bt = QtWidgets.QPushButton(self.widget_3)
        self.delete_bt.setGeometry(QtCore.QRect(50, 210, 93, 28))
        self.delete_bt.setObjectName("delete_bt")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.widget_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 170, 161, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.grade_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.grade_label.setText("")
        self.grade_label.setObjectName("grade_label")
        self.horizontalLayout_5.addWidget(self.grade_label)
        self.widget_3.raise_()
        self.widget_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "院系"))
        self.label_3.setText(_translate("Form", "性别"))
        self.label_1.setText(_translate("Form", "读者名："))
        self.label_2.setText(_translate("Form", "读者号："))
        self.delete_bt.setText(_translate("Form", "删除"))
        self.label_5.setText(_translate("Form", "年级"))

